//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_default : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean InteractUI
        {
            get
            {
                return SteamVR_Actions.default_InteractUI;
            }
        }
        
        public virtual SteamVR_Action_Boolean Teleport
        {
            get
            {
                return SteamVR_Actions.default_Teleport;
            }
        }
        
        public virtual SteamVR_Action_Boolean GrabPinch
        {
            get
            {
                return SteamVR_Actions.default_GrabPinch;
            }
        }
        
        public virtual SteamVR_Action_Boolean GrabGrip
        {
            get
            {
                return SteamVR_Actions.default_GrabGrip;
            }
        }
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.default_Pose;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonLeftHand
        {
            get
            {
                return SteamVR_Actions.default_SkeletonLeftHand;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonRightHand
        {
            get
            {
                return SteamVR_Actions.default_SkeletonRightHand;
            }
        }
        
        public virtual SteamVR_Action_Single Squeeze
        {
            get
            {
                return SteamVR_Actions.default_Squeeze;
            }
        }
        
        public virtual SteamVR_Action_Boolean HeadsetOnHead
        {
            get
            {
                return SteamVR_Actions.default_HeadsetOnHead;
            }
        }
        
        public virtual SteamVR_Action_Boolean SnapTurnLeft
        {
            get
            {
                return SteamVR_Actions.default_SnapTurnLeft;
            }
        }
        
        public virtual SteamVR_Action_Boolean SnapTurnRight
        {
            get
            {
                return SteamVR_Actions.default_SnapTurnRight;
            }
        }
        
        public virtual SteamVR_Action_Boolean SwitchMode
        {
            get
            {
                return SteamVR_Actions.default_SwitchMode;
            }
        }
        
        public virtual SteamVR_Action_Boolean createVoxel
        {
            get
            {
                return SteamVR_Actions.default_createVoxel;
            }
        }
        
        public virtual SteamVR_Action_Boolean DeleteVoxel
        {
            get
            {
                return SteamVR_Actions.default_DeleteVoxel;
            }
        }
        
        public virtual SteamVR_Action_Boolean selectVoxel
        {
            get
            {
                return SteamVR_Actions.default_selectVoxel;
            }
        }
        
        public virtual SteamVR_Action_Boolean pullFace
        {
            get
            {
                return SteamVR_Actions.default_pullFace;
            }
        }
        
        public virtual SteamVR_Action_Boolean createObject
        {
            get
            {
                return SteamVR_Actions.default_createObject;
            }
        }
        
        public virtual SteamVR_Action_Boolean copyObject
        {
            get
            {
                return SteamVR_Actions.default_copyObject;
            }
        }
        
        public virtual SteamVR_Action_Boolean moveObject
        {
            get
            {
                return SteamVR_Actions.default_moveObject;
            }
        }
        
        public virtual SteamVR_Action_Boolean rotateObject
        {
            get
            {
                return SteamVR_Actions.default_rotateObject;
            }
        }
        
        public virtual SteamVR_Action_Boolean combineObject
        {
            get
            {
                return SteamVR_Actions.default_combineObject;
            }
        }
        
        public virtual SteamVR_Action_Boolean selectObject
        {
            get
            {
                return SteamVR_Actions.default_selectObject;
            }
        }
        
        public virtual SteamVR_Action_Boolean selectFace
        {
            get
            {
                return SteamVR_Actions.default_selectFace;
            }
        }
        
        public virtual SteamVR_Action_Boolean deleteObject
        {
            get
            {
                return SteamVR_Actions.default_deleteObject;
            }
        }
        
        public virtual SteamVR_Action_Boolean worldMenu
        {
            get
            {
                return SteamVR_Actions.default_worldMenu;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.default_Haptic;
            }
        }
    }
}
